#!/bin/bash

thisdir="$(dirname "$0")"
source "$thisdir/program-runner-lib.sh"

if [ $# -eq 0 ]; then
    echo "Usage: program-runner-start [part of program name]\n"
    exit 1
fi

get_pid $1
kill -s USR1 $pid
