#!/bin/bash

thisdir="$(dirname "$0")"
source "$thisdir/program-runner-lib.sh"

if [ $# -eq 0 ]; then
    echo "Usage: program-runner-start [part of program name]\n"
    exit 1
fi

get_pid $1

if [[ -z $pid ]]; then
    echo "[program-runner] no program-runner instance found for '$1'"
    exit 1
fi

kill -s USR1 $pid
echo "[program-runner] send signal (SIGUSR1) to $pid ($name)"
